import React from 'react';
import { ShieldCheck, Fingerprint, Activity, Search, Lock, Zap } from 'lucide-react';

const features = [
  {
    title: "Advanced AI Video Detection",
    desc: "Our deepfake detector identifies content generated by state-of-the-art models like Sora, Runway Gen-3, Pika, and Kling. We verify video authenticity by analyzing subtle artifacts invisible to the naked eye.",
    icon: <Fingerprint className="w-6 h-6 text-cyan-400" />
  },
  {
    title: "Forensic Latent Analysis",
    desc: "Use our video forensics tool to map the 'latent space trajectory' of footage. Real videos follow consistent physical laws, while AI-generated videos often show erratic curvature and temporal inconsistencies.",
    icon: <Activity className="w-6 h-6 text-emerald-400" />
  },
  {
    title: "Verify News & Social Media",
    desc: "Is this news video real? Detect fake TikTok videos and verify YouTube clips instantly. Our media verification tool helps journalists and researchers fight misinformation and synthetic propaganda.",
    icon: <Search className="w-6 h-6 text-purple-400" />
  },
  {
    title: "High-Accuracy Physics Check",
    desc: "Unlike simple metadata checkers, our synthetic video detector evaluates physical coherence—gravity, lighting, and object permanence—to provide a highly accurate authenticity score.",
    icon: <ShieldCheck className="w-6 h-6 text-rose-400" />
  },
  {
    title: "Secure & Private Analysis",
    desc: "Your uploads are processed securely. We provide a reliable real or ai video checker that respects privacy while delivering enterprise-grade deepfake detection API capabilities.",
    icon: <Lock className="w-6 h-6 text-indigo-400" />
  },
  {
    title: "Instant Results",
    desc: "How to tell if a video is AI? Just upload or paste a link. Our system extracts frames and performs semantic analysis in seconds, giving you a clear 'Real' or 'Fake' verdict.",
    icon: <Zap className="w-6 h-6 text-yellow-400" />
  }
];

const HomeFeatures: React.FC = () => {
  return (
    <section className="mt-20 animate-fade-in">
      <h2 className="text-2xl font-bold text-center text-white mb-10">
        Why Choose FrameTruth for <span className="text-cyan-400">Video Authenticity</span>?
      </h2>
      
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
        {features.map((feature, idx) => (
          <div key={idx} className="bg-slate-900/30 border border-slate-800 p-6 rounded-xl hover:bg-slate-900/50 transition-colors">
            <div className="bg-slate-950 w-12 h-12 rounded-lg flex items-center justify-center mb-4 border border-slate-800">
              {feature.icon}
            </div>
            <h3 className="text-lg font-semibold text-white mb-2">{feature.title}</h3>
            <p className="text-sm text-slate-400 leading-relaxed">
              {feature.desc}
            </p>
          </div>
        ))}
      </div>
    </section>
  );
};

export default HomeFeatures;
